cc_library (
  name = "test-model",
  srcs = [
    "TestModel.cpp",
    "Input.cpp",
    "Json.cpp",
  ],
  deps = [
    "//thirdparty/json11:json11",
  ],
  export_incs = ["."],
  extra_cppflags = [
    "-std=gnu++11",
  ],
)
